// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-deploy/infra/mysql/model"
)

func newRelease(db *gorm.DB, opts ...gen.DOOption) release {
	_release := release{}

	_release.releaseDo.UseDB(db, opts...)
	_release.releaseDo.UseModel(&model.Release{})

	tableName := _release.releaseDo.TableName()
	_release.ALL = field.NewAsterisk(tableName)
	_release.ID = field.NewInt64(tableName, "id")
	_release.CreatedAt = field.NewTime(tableName, "created_at")
	_release.UpdatedAt = field.NewTime(tableName, "updated_at")
	_release.BusinessUnitID = field.NewInt64(tableName, "business_unit_id")
	_release.DeployPlanID = field.NewInt64(tableName, "deploy_plan_id")
	_release.CDConfigID = field.NewInt64(tableName, "cd_config_id")
	_release.BuildArtifactID = field.NewInt64(tableName, "build_artifact_id")
	_release.ImageRef = field.NewString(tableName, "image_ref")
	_release.Version = field.NewInt64(tableName, "version")
	_release.Status = field.NewString(tableName, "status")
	_release.RenderedYAML = field.NewString(tableName, "rendered_yaml")
	_release.RendererType = field.NewString(tableName, "renderer_type")
	_release.EngineType = field.NewString(tableName, "engine_type")
	_release.ReleaseStrategy = field.NewField(tableName, "release_strategy")

	_release.fillFieldMap()

	return _release
}

type release struct {
	releaseDo releaseDo

	ALL             field.Asterisk
	ID              field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	BusinessUnitID  field.Int64
	DeployPlanID    field.Int64
	CDConfigID      field.Int64
	BuildArtifactID field.Int64
	ImageRef        field.String
	Version         field.Int64
	Status          field.String
	RenderedYAML    field.String
	RendererType    field.String
	EngineType      field.String
	ReleaseStrategy field.Field

	fieldMap map[string]field.Expr
}

func (r release) Table(newTableName string) *release {
	r.releaseDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r release) As(alias string) *release {
	r.releaseDo.DO = *(r.releaseDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *release) updateTableName(table string) *release {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.BusinessUnitID = field.NewInt64(table, "business_unit_id")
	r.DeployPlanID = field.NewInt64(table, "deploy_plan_id")
	r.CDConfigID = field.NewInt64(table, "cd_config_id")
	r.BuildArtifactID = field.NewInt64(table, "build_artifact_id")
	r.ImageRef = field.NewString(table, "image_ref")
	r.Version = field.NewInt64(table, "version")
	r.Status = field.NewString(table, "status")
	r.RenderedYAML = field.NewString(table, "rendered_yaml")
	r.RendererType = field.NewString(table, "renderer_type")
	r.EngineType = field.NewString(table, "engine_type")
	r.ReleaseStrategy = field.NewField(table, "release_strategy")

	r.fillFieldMap()

	return r
}

func (r *release) WithContext(ctx context.Context) *releaseDo { return r.releaseDo.WithContext(ctx) }

func (r release) TableName() string { return r.releaseDo.TableName() }

func (r release) Alias() string { return r.releaseDo.Alias() }

func (r release) Columns(cols ...field.Expr) gen.Columns { return r.releaseDo.Columns(cols...) }

func (r *release) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *release) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["business_unit_id"] = r.BusinessUnitID
	r.fieldMap["deploy_plan_id"] = r.DeployPlanID
	r.fieldMap["cd_config_id"] = r.CDConfigID
	r.fieldMap["build_artifact_id"] = r.BuildArtifactID
	r.fieldMap["image_ref"] = r.ImageRef
	r.fieldMap["version"] = r.Version
	r.fieldMap["status"] = r.Status
	r.fieldMap["rendered_yaml"] = r.RenderedYAML
	r.fieldMap["renderer_type"] = r.RendererType
	r.fieldMap["engine_type"] = r.EngineType
	r.fieldMap["release_strategy"] = r.ReleaseStrategy
}

func (r release) clone(db *gorm.DB) release {
	r.releaseDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r release) replaceDB(db *gorm.DB) release {
	r.releaseDo.ReplaceDB(db)
	return r
}

type releaseDo struct{ gen.DO }

func (r releaseDo) Debug() *releaseDo {
	return r.withDO(r.DO.Debug())
}

func (r releaseDo) WithContext(ctx context.Context) *releaseDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r releaseDo) ReadDB() *releaseDo {
	return r.Clauses(dbresolver.Read)
}

func (r releaseDo) WriteDB() *releaseDo {
	return r.Clauses(dbresolver.Write)
}

func (r releaseDo) Session(config *gorm.Session) *releaseDo {
	return r.withDO(r.DO.Session(config))
}

func (r releaseDo) Clauses(conds ...clause.Expression) *releaseDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r releaseDo) Returning(value interface{}, columns ...string) *releaseDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r releaseDo) Not(conds ...gen.Condition) *releaseDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r releaseDo) Or(conds ...gen.Condition) *releaseDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r releaseDo) Select(conds ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r releaseDo) Where(conds ...gen.Condition) *releaseDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r releaseDo) Order(conds ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r releaseDo) Distinct(cols ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r releaseDo) Omit(cols ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r releaseDo) Join(table schema.Tabler, on ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r releaseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *releaseDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r releaseDo) RightJoin(table schema.Tabler, on ...field.Expr) *releaseDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r releaseDo) Group(cols ...field.Expr) *releaseDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r releaseDo) Having(conds ...gen.Condition) *releaseDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r releaseDo) Limit(limit int) *releaseDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r releaseDo) Offset(offset int) *releaseDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r releaseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *releaseDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r releaseDo) Unscoped() *releaseDo {
	return r.withDO(r.DO.Unscoped())
}

func (r releaseDo) Create(values ...*model.Release) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r releaseDo) CreateInBatches(values []*model.Release, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r releaseDo) Save(values ...*model.Release) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r releaseDo) First() (*model.Release, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Take() (*model.Release, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Last() (*model.Release, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) Find() ([]*model.Release, error) {
	result, err := r.DO.Find()
	return result.([]*model.Release), err
}

func (r releaseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Release, err error) {
	buf := make([]*model.Release, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r releaseDo) FindInBatches(result *[]*model.Release, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r releaseDo) Attrs(attrs ...field.AssignExpr) *releaseDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r releaseDo) Assign(attrs ...field.AssignExpr) *releaseDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r releaseDo) Joins(fields ...field.RelationField) *releaseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r releaseDo) Preload(fields ...field.RelationField) *releaseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r releaseDo) FirstOrInit() (*model.Release, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) FirstOrCreate() (*model.Release, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Release), nil
	}
}

func (r releaseDo) FindByPage(offset int, limit int) (result []*model.Release, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r releaseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r releaseDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r releaseDo) Delete(models ...*model.Release) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *releaseDo) withDO(do gen.Dao) *releaseDo {
	r.DO = *do.(*gen.DO)
	return r
}
